# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://reliefcloud.github.io/
title: Relief Cloud
email: dsfinan@gmail.com
description: > # "Building tools to facilitate the sharing of humanitarian relief information"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ReliefCloud
  - title: github
    url: https://github.com/ReliefCloud
  - title: linkedin
    url: 
